### ISSUE TITLE
Implement UI device setup

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/ha-glocaltokens#16]
**Is your feature request related to a problem? Please describe.**
I have been developing another integration with more or less the same idea in mind, it would be nice to join the two in this one, and not have multiple integrations with the same purpose laying around.

**Describe the solution you'd like**
Add the config_flow device setup and features of [ArnyminerZ/HomeAssistant-GoogleHome](https://github.com/ArnyminerZ/HomeAssistant-GoogleHome).

I'm working on implementing it, but there's quite a lot to adapt.

**Comment by DurgNomis-drol** [comment]
I was also building my own integration [See here](https://github.com/DurgNomis-drol/ha-google_home_local), until i found @leikoilja also were making. We have already decided to combine ours and i think it would be great if you would join us.

**Comment by DurgNomis-drol** [comment]
Setting up this integration works from the UI already. When you say device configurator, do you mean building a way to supply each device with an IP so we can connect to it. Homegraph does not include an IP of each device.

Please see my pull request and build up on that. So we dont do same work twice.

**Comment by ArnyminerZ** [comment]
I meant not having to add the REST device in `configuration.yaml`. Adding an UI to create all the GET from [GHLocalApi](https://rithvikvibhu.github.io/GHLocalApi) as sensors. But will stop working on this, since it's secondary, and start researching a "device discovery" way of getting the connected devices to the network, since I've just had an idea with the [`PyChromecast`](https://pypi.org/project/PyChromecast/) API.

**Comment by DurgNomis-drol** [comment]
Okay, my pull request and the integration i have build retrieves timers and alarms. The only thing that is need in that pull request i have made, is a way to retrieve an IP for each device so that It can create sensors for each device(Right now it only works for one device). There are also a couple of small things like getting the sensors to update( The API retrieves every 15 secs. But doesn't update the sensors for what ever reason)

It would be great if you could find a solution with `pychromecast` API

And a good idea with implementing the rest of the sensors, but I don't know if they are that useful

Sorry if I'm misunderstanding you and what you intend to do. It's great to have you onboard

**Comment by ArnyminerZ** [comment]
Yeah, will start working on that, I find it more important than the other, see #18.

Have just made an snippet that works flawlessly, so I will keep going in that way. Still have to do some research on how discovery works on Home Assistant, but I hope it won't be such a mistery.

**Comment by DurgNomis-drol** [comment]
Nice! This looks promising. I will test and help as soon as you have something.

How do we make sure that the discovered ip correlate with the same device in homegraph?

**Comment by leikoilja** [comment]
Nice, I m happy to see us collaborating together to make the HA integration work. 

@DurgNomis-drol, I have recently seen something interesting in homegraph. When `glocaltoken` package fetches tokens it can also extract local IP address (within your home network) from devices. We can extent `glocaltoken` client to fetch IPs per device together with tokens. The only problem is that those IPs are dynamic at most of the setups, but I guess we can just periodically fetch those and keep them in HA sensors together with tokens.

**Comment by ArnyminerZ** [comment]
> 
> 
> Nice, I m happy to see us collaborating together to make the HA integration work.
> 
> @DurgNomis-drol, I have recently seen something interesting in homegraph. When `glocaltoken` package fetches tokens it can also extract local IP address (within your home network) from devices. We can extent `glocaltoken` client to fetch IPs per device together with tokens. The only problem is that those IPs are dynamic at most of the setups, but I guess we can just periodically fetch those and keep them in HA sensors together with tokens.

I was hoping that was an option, but didn't find it 😮. Maybe I didn't find hard enough. In that case, i don't think `PyChromecast` is necessary, everything, even autodiscovery could be done directly with `glocaltoken`, which would be really convenient. Maybe opening a new issue there regarding device discovery?

**Comment by DurgNomis-drol** [comment]
See #18

**Comment by leikoilja** [comment]
This is probably not needed anymore. Feel free to reopen if otherwise
