### ISSUE TITLE
Do not hammer Google Oauth API

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-glocaltokens#17]
**Describe the solution you'd like**
Make sure that we are not hammering the Google Oauth when trying to retrieve master_token, access_token and localAuthToken.

**Comment by ArnyminerZ** [comment]
If I'm not wrong, this is done through the `glocaltokens` API, so it should be partially solved as stated in [issue 9](https://github.com/leikoilja/glocaltokens/pull/9).

As far as I've seen, the master token is gotten [here](https://github.com/leikoilja/ha-glocaltokens/blob/2531b71e3329a50b67a4065d47e299328254ff06/custom_components/ha-glocaltokens/api.py#L34), so simply the `glocaltokens` API should be updated.

**Comment by ArnyminerZ** [comment]
Also, isn't the `GlocaltokensApiClient` class a bit redundant in [`api.py`](https://github.com/leikoilja/ha-glocaltokens/blob/master/custom_components/ha-glocaltokens/api.py#L17)? I believe `GLocalAuthenticationTokens` from `glocaltokens.client` should be used instead.

**Comment by DurgNomis-drol** [comment]
Yes it is, api.py should only contain the API for getting information from devices. glocaltoken is then rest.

See my file [api.py](https://github.com/DurgNomis-drol/ha-glocaltokens/blob/master/custom_components/ha-glocaltokens/api.py)

This was mostly made as an reference so we would remember to implement it correctly.

**Comment by ArnyminerZ** [comment]
Ok, I'm working on adding a device configurator from the UI, will update at #16

**Comment by leikoilja** [comment]
Agreed, the initial implementation of `GlocaltokensApiClient` is a bit redundant, but hopefully, it will grow as the integration grows. The current file structure was mostly followed HA integration blueprint and that class was left there as a placeholder

**Comment by ArnyminerZ** [comment]
So I think it would be better to simply work on `glocaltokens` as a library, that is used by `ha-glocaltokens`, so code won't be doubled, and improvements on `glocaltokens` would serve for `ha-glocaltokens`.

**Comment by DurgNomis-drol** [comment]
Yes, some of things should be moved into `glocaltokens` instead. Should we wait until we have #11 merged? Discovery of the IP is what is holding back the integration from working very well

**Comment by leikoilja** [comment]
The initial issue of hammering Google APIs should be fixed now in `glocaltokens`, see https://github.com/leikoilja/glocaltokens/issues/3.
