### ISSUE TITLE
[dev] Implement IP address autodiscovery (zeroconf)

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/ha-glocaltokens#18]
Discovery should be implemented, in order to detect the Google Home device's IP. By using the `pychromecast` API, this can be achieved, for example, with the following snippet:

```python
import pychromecast

VALID_GOOGLE_HOME_MODELS = [
    "Google Home",
    "Google Home Mini",
    "Lenovo Smart Clock"
]


def discover_google_home():
    print("Discovering Google Homes...")
    services, browser = pychromecast.discovery.discover_chromecasts()
    for service in services:
        model = service[2]
        name = service[3]
        ip = service[4]
        access_port = service[5]
        if model in VALID_GOOGLE_HOME_MODELS:
            print(f"{name} ({ip}:{access_port}) - {model}")
            print()

```
The port is more or less useless, since as far as I know, for every Google Home the port is the same: `8009`, but, who knows.

This should be added to the integration in the `discovery.py` file, as stated by the [Home Assistant documentation](https://developers.home-assistant.io/docs/).

I will start working on that, and see if we can make the device configuration easier.

**Comment by leikoilja** [comment]
I like the idea of auto discovery! I guess for now we can simply utilize `glocaltokens` package to get IP addresses (See https://github.com/leikoilja/ha-glocaltokens/issues/16#issuecomment-776796188), but auto discovery would be a whole new level 😎

**Comment by DurgNomis-drol** [comment]
Nice, that solves the problem then. I also tried to find it in homegraph but couldn't, do you have some information on how?

**Comment by leikoilja** [comment]
I will try digging in tonight, will keep you posted if I ll find a way how to. Will probably implement it into `glocaltoken` right away, if I ll be able to find those :)

**Comment by DurgNomis-drol** [comment]
what about hostnames? can we compare hostname in homegraph to a hostname found with pychromcast? or are there other identifiers?

**Comment by leikoilja** [comment]
I ll try to dig deeper tomorrow into homegraph, because somehow I remember seeing the IP addresses of devices somewhere 😄  I can't just let it go now

**Comment by ArnyminerZ** [comment]
> 
> 
> what about hostnames? can we compare hostname in homegraph to a hostname found with pychromcast? or are there other identifiers?

I think in that case it's easier to simply show the user a list of devices from `pychromecast`, and then create a relation between the "display name" in pychromecast and in Homegraph, since they should be the same.

**Comment by ArnyminerZ** [comment]
> 
> 
> I ll try to dig deeper tomorrow into homegraph, because somehow I remember seeing the IP addresses of devices somewhere 😄 I can't just let it go now

By looking at the [RPC API docs](https://developers.google.com/assistant/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.Device) I can't find anything about an IP address...

**Comment by DurgNomis-drol** [comment]
Using mDNS(pychromecast) we can make an reverse lookup and get the IP from that. If we can find I'd string in homegraph. Then we can make an reverse lookup with socket.gethostbyname in python by adding ._tcp.local afterwards. But I don't know if this will work or if homegraph has this string included

**Comment by ArnyminerZ** [comment]
I've implemented some code at the [`glocaltokens`](https://github.com/leikoilja/glocaltokens/pull/13) repository. Did some testing and it seems to work pretty well.

**Comment by ArnyminerZ** [comment]
For now, will move the conversation to [`glocaltokens`](https://github.com/leikoilja/glocaltokens/pull/13) and once it's implemented there, we will start working at `ha-glocaltokens`. Will reopen as soon as it's ready there.

**Comment by DurgNomis-drol** [comment]
Waiting for glocaltokens to merge device discovery. See [here](https://github.com/leikoilja/glocaltokens/pull/13)

**Comment by leikoilja** [comment]
@DurgNomis-drol, device discovery in `glocaltokens` is merged, thanks to @ArnyminerZ. Now we should look deeper into whether we can use that functionality straight from `glocaltokens` or we should utilize HA build-in mechanisms as described here: https://developers.home-assistant.io/docs/creating_integration_manifest/#zeroconf

**Comment by DurgNomis-drol** [comment]
I don't think there is any reason to duplicate his work. The only reason that we need discovery in the first place was because of the IP address. I have already made sure that dev branch should work, we just have to delete 1 line and we are done.

**Comment by leikoilja** [comment]
Sounds good, @DurgNomis-drol. Do you want to take a lead on this one? (If so, please just assign yourself to the ticket) 💥

**Comment by DurgNomis-drol** [comment]
Yes I will do that

Off topic, do we only aim to implement this as a custom component or do we aim to get it include in the official release?

**Comment by ArnyminerZ** [comment]
> @DurgNomis-drol, device discovery in `glocaltokens` is merged, thanks to @ArnyminerZ. Now we should look deeper into whether we can use that functionality straight from `glocaltokens` or we should utilize HA build-in mechanisms as described here: https://developers.home-assistant.io/docs/creating_integration_manifest/#zeroconf


I think that shouldn't be needed, unless we want to do like chromecast does, which detects devices in the network without having to search for them, which would be quite useful.

**Comment by DurgNomis-drol** [comment]
It already does this :smile:

**Comment by leikoilja** [comment]
@DurgNomis-drol, do you mean that it already detects chromecasts as well?

**Comment by DurgNomis-drol** [comment]
Everytime it updates it self, it checks if glocaltokens have found a new google home device and then adds it and create sensor, or it removes it if it know longer exists

**Comment by leikoilja** [comment]
Right! Nevermind, I think i got confused for a second.

Anyways, do you guys think we should leave "utilizing HA zeroconf" for later as a "future enhancement"?

**Comment by leikoilja** [comment]
Closed in https://github.com/leikoilja/glocaltokens/pull/13
