### ISSUE TITLE
Repo/Integration renaming -> ha-google-home

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-glocaltokens#19]
Now that we are adding more features like alarms/timers fetching, this repo is no longer makes sense to be called `ha-glocaltokens`, cause it's not just tokens we are fetching. How about we rename this repo into something like `ha-google-home`? Or is it too big of a shot? Anyways, let's discuss it here, @DurgNomis-drol, @ArnyminerZ

**Comment by DurgNomis-drol** [comment]
I really like ha-google-home, but i dont know if HA will allow that name

**Comment by ArnyminerZ** [comment]
I think `ha-google-home` is pretty convenient, and Home Assistant used to have a Google Home extension, so I don't think that would be a big deal to accept.

**Comment by leikoilja** [comment]
Sweet, let's try doing that! Will open a PR for that in the next few days when the open PR is merged
