### ISSUE TITLE
Cannot configure integration

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/ha-glocaltokens#22]
## Version of the custom_component
Latest on `master`

## Configuration
`configuration.yaml`
```yaml
...
ha-glocaltokens:
...
```

## Describe the bug
When trying to configure the integration through the add integration UI (`config_flow`), the window goes back to the integrations list.

## Debug log
In the browser, I get:
```json
{
"body": { "message": "Invalid handler specified" },
"error": "Response error: 404",
"status_code": "404"
}
```
More request info:\
*Contents:*
```json
{"handler":"ha-glocaltokens","show_advanced_options":false}
```
*Cookies:*
```text
Idea-48b7ff8d | "41ae16d5-eebc-40f1-9a3b-c035f087e00b"
```
*Headers:*
```text
XHRPOSThttp://localhost:8123/api/config/config_entries/flow
[HTTP/1.1 404 Not Found 1ms]

POST
	http://localhost:8123/api/config/config_entries/flow
Estado 404 Not Found
Versión HTTP/1.1
Transferido 224 B (tamaño 40 B)
Política de referencia same-origin

    Content-Encoding
    	deflate
    Content-Length
    	48
    Content-Type
    	application/json
    Date
    	Sat, 13 Feb 2021 12:30:55 GMT
    Server
    	Python/3.8 aiohttp/3.7.3
    	
    POST /api/config/config_entries/flow HTTP/1.1

    Host: localhost:8123

    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0

    Accept: */*

    Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3

    Accept-Encoding: gzip, deflate

    Content-Type: application/json;charset=UTF-8

    Content-Length: 59

    HA-Frontend-Base: http://localhost:8123

    Origin: http://localhost:8123

    DNT: 1

    Sec-GPC: 1

    authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhYWQxMGNjZGVjMjI0MGNhOGFjNzBiNmQ4Y2IyZDY0MiIsImlhdCI6MTYxMzIxODk4NywiZXhwIjoxNjEzMjIwNzg3fQ.u7W9c4EF_kLZHWwd4bJQO1tW0rG1k-EwjCYc_AfoCS4

    Referer: http://localhost:8123/config/integrations

    Connection: keep-alive

    Cookie: Idea-48b7ff8d=41ae16d5-eebc-40f1-9a3b-c035f087e00b
```

**Comment by leikoilja** [comment]
I have actually noticed similar problem yesterday and honestly don't think the integration is yet ready to be tested/used 😄 😕  There is a bug with how `get_android_id` is working on `glocaltokens` and that might be the reason why `ha-glocaltokens` fails to initialize. I suggest we focus on `glocaltokens` to merge and hanging PRs and changes to make it more robust first. And then we get back to `ha-glocaltokens`, rename the repo and get together to polish it 😄

**Comment by DurgNomis-drol** [comment]
On some systems `get_android_id` does not generate a valid mac, why, i dont know, but i had this problem som time ago. It only seems to exists on some problems, not others. My laptop does work, but my raspberry pi does.

**Comment by leikoilja** [comment]
Yeh, that's exactly the issue I have found out. I will fix it today with a new PR of `glocaltokens`

**Comment by ArnyminerZ** [comment]
Ok, so I will wait paciently and keep working on `glocaltokens`, just wanted to take a look for researching about discovery. Will leave the issue open just for reference on the progress of the `get_android_id` fix.

**Comment by DurgNomis-drol** [comment]
Discovery is pretty much done(See dev branch), I'm just waiting for glocaltokens to be updated and a new release is made with discovery included.
